/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlaySlugRouteImport } from './routes/play.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySlugRoute = PlaySlugRouteImport.update({
  id: '/play/$slug',
  path: '/play/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convert': typeof ConvertRoute
  '/courses': typeof CoursesRoute
  '/settings': typeof SettingsRoute
  '/play/$slug': typeof PlaySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convert': typeof ConvertRoute
  '/courses': typeof CoursesRoute
  '/settings': typeof SettingsRoute
  '/play/$slug': typeof PlaySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convert': typeof ConvertRoute
  '/courses': typeof CoursesRoute
  '/settings': typeof SettingsRoute
  '/play/$slug': typeof PlaySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/convert' | '/courses' | '/settings' | '/play/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/convert' | '/courses' | '/settings' | '/play/$slug'
  id: '__root__' | '/' | '/convert' | '/courses' | '/settings' | '/play/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertRoute: typeof ConvertRoute
  CoursesRoute: typeof CoursesRoute
  SettingsRoute: typeof SettingsRoute
  PlaySlugRoute: typeof PlaySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$slug': {
      id: '/play/$slug'
      path: '/play/$slug'
      fullPath: '/play/$slug'
      preLoaderRoute: typeof PlaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertRoute: ConvertRoute,
  CoursesRoute: CoursesRoute,
  SettingsRoute: SettingsRoute,
  PlaySlugRoute: PlaySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
