import type { Room } from "./schema";

export const httpBasicsRoom: Room = {
  schema_version: "1.0",
  service: "Roomish",
  room: {
    id: "room-http-basics",
    title: "HTTP in one sitting",
    slug: "http-basics",
    topic: "HTTP request and response basics",
    audience: "beginner",
    estimated_minutes: 12,
    language: "en",
    learning_objectives: [
      "Name the two sides of an HTTP exchange",
      "Identify a method and a status code",
      "Read a path on the request line",
    ],
    intro:
      "How a browser talks to a server. You will read a request, name its parts, and recognise a status code.",
    tags: ["web", "http"],
  },
  tasks: [
    {
      id: "T1",
      title: "What is HTTP doing?",
      teach:
        "HTTP is a **request-response** protocol.\n\nA *client* sends a request. A *server* returns a response. Your browser is usually the client.",
      checks: [
        {
          qid: "T1-Q1",
          type: "short",
          prompt: "What term describes the component of a web application rendered by your browser?",
          stem_note: "Answer with the two-word term.",
          choices: [],
          blanks: [],
          pairs_left: [],
          pairs_right: [],
          answer: "front end",
          accepted: ["front end", "frontend", "front-end"],
          case_sensitive: false,
          points: 10,
          hint: "It is the side the user sees.",
          explain: "The front end is what the browser renders. The back end runs on the server.",
        },
      ],
    },
    {
      id: "T2",
      title: "The request line",
      teach:
        "The first line of an HTTP request has three parts: method, path, and version.\n\n```http\nGET /login HTTP/1.1\n```\n\n- `GET` is the method\n- `/login` is the path\n- `HTTP/1.1` is the version",
      checks: [
        {
          qid: "T2-Q1",
          type: "mcq",
          prompt: "Which method asks the server for a resource without sending a body?",
          stem_note: "",
          choices: ["A) POST", "B) GET", "C) PUT", "D) PATCH"],
          blanks: [],
          pairs_left: [],
          pairs_right: [],
          answer: "B) GET",
          accepted: ["B", "B) GET", "GET"],
          case_sensitive: false,
          points: 10,
          hint: "It is the method your browser uses when you type a URL.",
          explain: "GET retrieves. POST, PUT, and PATCH send or change data.",
        },
        {
          qid: "T2-Q2",
          type: "fill",
          prompt: "Complete: GET /login HTTP/1.1 — the path is ________.",
          stem_note: "Include the leading slash.",
          choices: [],
          blanks: [{ id: "b1", before: "the path is ", after: "." }],
          pairs_left: [],
          pairs_right: [],
          answer: "/login",
          accepted: ["/login"],
          case_sensitive: false,
          points: 10,
          hint: "It starts with a slash.",
          explain: "The path is the resource target. Here that is /login.",
        },
      ],
    },
    {
      id: "T3",
      title: "Status codes",
      teach: "A response starts with a status code. 200 means OK. 404 means the path was not found. 500 means the server failed.",
      checks: [
        {
          qid: "T3-Q1",
          type: "true_false",
          prompt: "A 404 status code means the server itself crashed.",
          stem_note: "",
          choices: [],
          blanks: [],
          pairs_left: [],
          pairs_right: [],
          answer: "False",
          accepted: ["False", "F"],
          case_sensitive: false,
          points: 10,
          hint: "Crash codes live in the 5xx class.",
          explain: "404 is client-side not found. 5xx is server error.",
        },
      ],
    },
  ],
  recap: {
    key_terms: [
      "front end: what the browser renders",
      "GET: retrieve a resource",
      "404: path not found",
    ],
    common_mistakes: ["Calling every failure a 500", "Mixing path and host"],
    next_room_ideas: ["HTTP headers", "Cookies and sessions"],
  },
};

export const photosynthesisRoom: Room = {
  schema_version: "1.0",
  service: "Roomish",
  room: {
    id: "room-photosynthesis",
    title: "Photosynthesis for year 8",
    slug: "photosynthesis-year-8",
    topic: "Photosynthesis",
    audience: "beginner",
    estimated_minutes: 10,
    language: "en",
    learning_objectives: [
      "Name the inputs and outputs of photosynthesis",
      "Locate where it happens in a plant cell",
    ],
    intro: "A short lesson on how plants make food from light. Read each page, then answer.",
    tags: ["biology", "science"],
  },
  tasks: [
    {
      id: "T1",
      title: "The word equation",
      teach:
        "Photosynthesis uses carbon dioxide and water. Light energy drives the reaction. The products are glucose and oxygen. It happens in chloroplasts.\n\nThe symbol equation is\n\n$$\n6CO_2 + 6H_2O \\xrightarrow{\\text{light}} C_6H_{12}O_6 + 6O_2\n$$\n\nIn words: carbon dioxide + water $\\rightarrow$ glucose + oxygen.",
      checks: [
        {
          qid: "T1-Q1",
          type: "mcq",
          prompt: "Which organelle is the main site of photosynthesis?",
          stem_note: "",
          choices: ["A) Mitochondrion", "B) Nucleus", "C) Chloroplast", "D) Vacuole"],
          blanks: [],
          pairs_left: [],
          pairs_right: [],
          answer: "C) Chloroplast",
          accepted: ["C", "C) Chloroplast", "chloroplast"],
          case_sensitive: false,
          points: 10,
          hint: "It is green.",
          explain: "Chloroplasts contain chlorophyll and run photosynthesis.",
        },
        {
          qid: "T1-Q2",
          type: "short",
          prompt: "Name one gas that plants release as a product of photosynthesis.",
          stem_note: "One word.",
          choices: [],
          blanks: [],
          pairs_left: [],
          pairs_right: [],
          answer: "oxygen",
          accepted: ["oxygen", "O2", "O₂"],
          case_sensitive: false,
          points: 10,
          hint: "Animals breathe it in.",
          explain: "Oxygen is released. Carbon dioxide is an input, not a product.",
        },
      ],
    },
    {
      id: "T2",
      title: "Match the parts",
      teach: "Chlorophyll absorbs light. Stomata on leaves let gases in and out. Glucose is stored or used in respiration.",
      checks: [
        {
          qid: "T2-Q1",
          type: "matching",
          prompt: "Match each item to its role.",
          stem_note: "Use the form left => right; left => right",
          choices: [],
          blanks: [],
          pairs_left: ["chlorophyll", "stomata", "glucose"],
          pairs_right: ["absorbs light", "gas exchange", "sugar product"],
          answer:
            "chlorophyll => absorbs light; stomata => gas exchange; glucose => sugar product",
          accepted: [
            "chlorophyll => absorbs light; stomata => gas exchange; glucose => sugar product",
          ],
          case_sensitive: false,
          points: 10,
          hint: "Think green pigment, leaf pores, food.",
          explain: "Chlorophyll traps light, stomata swap gases, glucose is the sugar made.",
        },
      ],
    },
  ],
  recap: {
    key_terms: [
      "chloroplast: organelle where photosynthesis happens",
      "chlorophyll: pigment that absorbs light",
    ],
    common_mistakes: ["Listing oxygen as an input"],
    next_room_ideas: ["Respiration", "Leaf structure"],
  },
};

export const SAMPLE_ROOMS: Room[] = [httpBasicsRoom, photosynthesisRoom];
